//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.01 at 06:32:57 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.hilalaissani.com/spring-soap-example",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package javaspringsoapwebservice.userGeneratedFromXML;
